'use client'

import { useState } from 'react'
import {
  ArrowRight,
  BarChart3,
  Check,
  ChevronDown,
  Code2,
  Globe2,
  Menu,
  Play,
  ShieldCheck,
  Sparkles,
  X,
  Zap,
} from 'lucide-react'

const features = [
  { icon: BarChart3, title: 'Real-time transaction tracking', text: 'See every payment, refund, and payout as it happens. No more waiting for end-of-day reports.', accent: 'violet' },
  { icon: ShieldCheck, title: 'Fraud detection alerts', text: 'Spot suspicious patterns early with intelligent alerts that help your team act with confidence.', accent: 'mint' },
  { icon: Globe2, title: 'Multi-currency support', text: 'Track global revenue in 135+ currencies with effortless conversion and consolidated reporting.', accent: 'blue' },
  { icon: Code2, title: 'Developer-friendly API', text: 'Build your own workflows with clean docs, predictable endpoints, and webhooks that just work.', accent: 'orange' },
]

const plans = [
  { name: 'Starter', price: '$0', description: 'For teams getting a clearer view of their payments.', features: ['Up to 1,000 transactions', '7-day data history', 'Core analytics', 'Email support'] },
  { name: 'Growth', price: '$149', description: 'For scaling businesses that need sharper insights.', features: ['Up to 50,000 transactions', '2-year data history', 'Fraud detection alerts', 'Multi-currency reporting', 'Priority support'], featured: true },
  { name: 'Enterprise', price: 'Custom', description: 'For global teams with complex payment operations.', features: ['Unlimited transactions', 'Unlimited data history', 'Custom reporting', 'Dedicated success manager', 'SLA & SSO'] },
]

function Logo() { return <a href="#top" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground"><Zap className="size-4 fill-current" /></span><span className="text-lg">paylytics<span className="text-primary">.</span></span></a> }

function DashboardPreview() {
  return <div className="dashboard-card animate-float relative mx-auto w-full max-w-[560px] overflow-hidden rounded-2xl border bg-card shadow-2xl shadow-primary/10">
    <div className="flex items-center justify-between border-b px-5 py-4"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-primary" /><span className="text-sm font-medium">Overview</span></div><span className="rounded-md border px-2.5 py-1 text-xs text-muted-foreground">Last 30 days <ChevronDown className="ml-1 inline size-3" /></span></div>
    <div className="grid grid-cols-3 gap-3 p-5"><div><p className="text-xs text-muted-foreground">Gross volume</p><p className="mt-1 text-xl font-semibold tracking-tight">$482,904</p><p className="mt-1 text-xs font-medium text-mint">+18.4%</p></div><div><p className="text-xs text-muted-foreground">Transactions</p><p className="mt-1 text-xl font-semibold tracking-tight">24,892</p><p className="mt-1 text-xs font-medium text-mint">+12.8%</p></div><div><p className="text-xs text-muted-foreground">Success rate</p><p className="mt-1 text-xl font-semibold tracking-tight">98.6%</p><p className="mt-1 text-xs font-medium text-mint">+1.2%</p></div></div>
    <div className="px-5 pb-5"><div className="relative h-40 overflow-hidden rounded-xl bg-muted/60 p-4"><div className="flex h-full items-end gap-2">{[38,52,42,64,56,74,67,82,70,94,78,100,89,92,84,108,96,114,104,120].map((h,i)=><div key={i} className="chart-bar flex-1 rounded-t-sm bg-primary/80" style={{height:`${h}px`, opacity: .45 + i/40}} />)}</div><div className="pointer-events-none absolute inset-x-4 top-1/2 border-t border-dashed border-primary/20" /></div><div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><span>May 08</span><span>May 15</span><span>May 22</span><span>May 29</span></div></div>
    <div className="mx-5 mb-5 flex items-center justify-between rounded-xl border bg-background px-4 py-3"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-mint/15 text-mint"><Check className="size-4" /></span><div><p className="text-xs font-medium">Payment received</p><p className="text-[11px] text-muted-foreground">Acme Inc. · just now</p></div></div><span className="text-sm font-semibold">+$2,480</span></div>
  </div>
}

function FeatureCard({ feature }: { feature: typeof features[number] }) { const Icon = feature.icon; return <article className="group rounded-2xl border bg-card p-6 transition-all hover:-translate-y-1 hover:shadow-lg"><span className={`feature-icon ${feature.accent}`}><Icon className="size-5" /></span><h3 className="mt-6 text-lg font-semibold tracking-tight">{feature.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{feature.text}</p><a className="mt-5 inline-flex items-center gap-1 text-sm font-medium text-primary opacity-0 transition-opacity group-hover:opacity-100" href="#pricing">Learn more <ArrowRight className="size-4" /></a></article> }

export default function Page() {
  const [open, setOpen] = useState(false)
  return <main id="top" className="overflow-hidden">
    <nav className="sticky top-0 z-20 border-b bg-background/85 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8"><Logo /><div className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#features" className="hover:text-foreground">Product</a><a href="#pricing" className="hover:text-foreground">Pricing</a><a href="#stories" className="hover:text-foreground">Customers</a><a href="#developers" className="hover:text-foreground">Developers</a></div><div className="hidden items-center gap-5 md:flex"><a href="#contact" className="text-sm text-muted-foreground hover:text-foreground">Sign in</a><a href="#pricing" className="rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground transition-transform hover:scale-105">Start for free</a></div><button aria-label={open ? 'Close menu' : 'Open menu'} className="md:hidden" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div>{open && <div className="flex flex-col gap-5 border-t px-5 py-5 text-sm md:hidden"><a href="#features" onClick={() => setOpen(false)}>Product</a><a href="#pricing" onClick={() => setOpen(false)}>Pricing</a><a href="#stories" onClick={() => setOpen(false)}>Customers</a><a href="#developers" onClick={() => setOpen(false)}>Developers</a></div>}</nav>
    <section className="hero-grid relative"><div className="mx-auto grid max-w-6xl items-center gap-14 px-5 py-20 lg:grid-cols-[1fr_1fr] lg:px-8 lg:py-28"><div className="relative z-10"><div className="eyebrow"><Sparkles className="size-3.5" /> The smarter way to see payments</div><h1 className="mt-7 max-w-xl text-balance text-5xl font-semibold tracking-[-0.055em] sm:text-6xl lg:text-7xl">Every payment tells a <span className="text-primary">story.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-muted-foreground">Paylytics turns your payment data into decisions. Track performance, catch fraud, and grow with clarity.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#pricing" className="inline-flex items-center justify-center gap-2 rounded-full bg-primary px-6 py-3.5 font-medium text-primary-foreground shadow-lg shadow-primary/20 transition-transform hover:scale-105">Start analyzing free <ArrowRight className="size-4" /></a><a href="#features" className="inline-flex items-center justify-center gap-2 rounded-full border px-6 py-3.5 font-medium hover:bg-muted"><Play className="size-4 fill-current" /> See how it works</a></div><p className="mt-5 text-xs text-muted-foreground">No credit card required · Setup in 2 minutes</p></div><DashboardPreview /></div></section>
    <section className="border-y bg-card/50"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-center gap-x-10 gap-y-5 px-5 py-7 text-sm text-muted-foreground lg:justify-between lg:px-8"><span className="font-medium">Trusted by teams at</span><span className="font-semibold tracking-tight">vertex<span className="text-primary">.</span></span><span className="font-semibold tracking-tight">NORTHSTAR</span><span className="font-semibold tracking-tight">arc<span className="text-primary">/</span>labs</span><span className="font-semibold tracking-tight">MODERNCO</span><span className="font-semibold tracking-tight">KITE</span></div></section>
    <section id="features" className="mx-auto max-w-6xl px-5 py-24 lg:px-8 lg:py-32"><div className="max-w-2xl"><p className="section-kicker">Built for better decisions</p><h2 className="mt-4 text-balance text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Your payments, <span className="text-primary">decoded.</span></h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Everything you need to understand what is happening beneath the surface of your revenue.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2">{features.map(f => <FeatureCard key={f.title} feature={f} />)}</div></section>
    <section id="pricing" className="bg-ink py-24 text-ink-foreground lg:py-32"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="section-kicker light">Simple, transparent pricing</p><h2 className="mt-4 text-balance text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Start small. <span className="text-mint">Scale smart.</span></h2></div><p className="max-w-xs text-sm leading-6 text-ink-muted">All plans include secure infrastructure and a 14-day Growth trial.</p></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{plans.map(plan => <div key={plan.name} className={`rounded-2xl border p-7 ${plan.featured ? 'border-mint bg-mint text-ink' : 'border-ink-border bg-ink-card'}`}><div className="flex items-center justify-between"><h3 className="text-xl font-semibold">{plan.name}</h3>{plan.featured && <span className="rounded-full bg-ink px-3 py-1 text-xs font-medium text-mint">Most popular</span>}</div><p className={`mt-3 min-h-12 text-sm leading-6 ${plan.featured ? 'text-ink/65' : 'text-ink-muted'}`}>{plan.description}</p><p className="mt-7 text-4xl font-semibold tracking-tight">{plan.price}{plan.price !== 'Custom' && <span className={`text-sm font-normal ${plan.featured ? 'text-ink/55' : 'text-ink-muted'}`}> / month</span>}</p><a href="#contact" className={`mt-7 flex items-center justify-center rounded-full px-4 py-3 text-sm font-medium ${plan.featured ? 'bg-ink text-mint' : 'border border-ink-border hover:bg-ink-border'}`}>{plan.price === 'Custom' ? 'Talk to sales' : 'Start free trial'}</a><div className={`my-7 border-t ${plan.featured ? 'border-ink/15' : 'border-ink-border'}`} /><ul className="flex flex-col gap-4 text-sm">{plan.features.map(item => <li key={item} className="flex items-start gap-3"><Check className={`mt-0.5 size-4 shrink-0 ${plan.featured ? 'text-ink' : 'text-mint'}`} />{item}</li>)}</ul></div>)}</div></div></section>
    <section id="stories" className="mx-auto max-w-6xl px-5 py-24 lg:px-8 lg:py-32"><div className="flex items-center justify-between"><div><p className="section-kicker">Loved by operators</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em]">Don&apos;t just take our word for it.</h2></div><span className="hidden text-sm text-muted-foreground sm:block">01 / 03</span></div><div className="mt-14 grid gap-4 md:grid-cols-3"><figure className="rounded-2xl bg-primary p-7 text-primary-foreground md:col-span-2"><blockquote className="max-w-xl text-2xl font-medium leading-9 tracking-tight">“Paylytics gave us the confidence to move from reacting to our numbers to actually planning around them.”</blockquote><figcaption className="mt-12 flex items-center gap-3 text-sm"><span className="grid size-10 place-items-center rounded-full bg-primary-foreground/15 font-semibold">JM</span><span><strong className="block">Jamie Morgan</strong><span className="opacity-70">VP Finance, Vertex</span></span></figcaption></figure><figure className="rounded-2xl border bg-card p-7"><blockquote className="text-lg font-medium leading-8">“The first dashboard our whole team actually wants to open.”</blockquote><figcaption className="mt-14 flex items-center gap-3 text-sm"><span className="grid size-10 place-items-center rounded-full bg-mint/20 font-semibold text-mint">AL</span><span><strong className="block">Alex Lee</strong><span className="text-muted-foreground">COO, Kite</span></span></figcaption></figure></div></section>
    <section id="contact" className="mx-5 mb-20 rounded-3xl bg-muted px-6 py-16 text-center sm:px-12 lg:mx-auto lg:max-w-6xl"><p className="section-kicker">Ready when you are</p><h2 className="mx-auto mt-4 max-w-2xl text-balance text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Make your next payment insight your best one.</h2><p className="mx-auto mt-5 max-w-lg text-muted-foreground">Join thousands of teams building a clearer picture of their business.</p><a href="#pricing" className="mt-8 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3.5 font-medium text-primary-foreground">Get started free <ArrowRight className="size-4" /></a></section>
    <footer className="border-t"><div className="mx-auto flex max-w-6xl flex-col gap-10 px-5 py-12 lg:px-8"><div className="flex flex-col justify-between gap-8 sm:flex-row"><div><Logo /><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">Payment intelligence for the businesses moving the world forward.</p></div><div className="grid grid-cols-2 gap-x-14 gap-y-8 text-sm sm:grid-cols-3"><div className="flex flex-col gap-3"><span className="font-medium">Product</span><a href="#features" className="text-muted-foreground">Features</a><a href="#pricing" className="text-muted-foreground">Pricing</a></div><div className="flex flex-col gap-3"><span className="font-medium">Company</span><a href="#stories" className="text-muted-foreground">Customers</a><a href="#contact" className="text-muted-foreground">Contact</a></div><div id="developers" className="flex flex-col gap-3"><span className="font-medium">Developers</span><a href="#developers" className="text-muted-foreground">Documentation</a><a href="#developers" className="text-muted-foreground">API status</a></div></div></div><div className="flex flex-col justify-between gap-4 border-t pt-6 text-xs text-muted-foreground sm:flex-row"><span>© 2025 Paylytics, Inc. All rights reserved.</span><div className="flex gap-5"><a href="#top">LinkedIn</a><a href="#top">X / Twitter</a><a href="#top">GitHub</a></div></div></div></footer>
  </main>
}
